--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/promitheas/Pictures/ocean_darker.jpg"

-- Special
background="#030C1C"
foreground="#1f74e5"
cursor="#1f74e5"

-- Colors
color0="#030C1C"
color1="#263C87"
color2="#2F4598"
color3="#454AC6"
color4="#595AEE"
color5="#664FFB"
color6="#5D90FD"
color7="#1f74e5"
color8="#7b90ac"
color9="#263C87"
color10="#2F4598"
color11="#454AC6"
color12="#595AEE"
color13="#664FFB"
color14="#5D90FD"
color15="#1f74e5"
