# Shell variables
# Generated by 'wal'
wallpaper='/home/promitheas/Pictures/ocean_darker.jpg'

# Special
background='#030C1C'
foreground='#1f74e5'
cursor='#1f74e5'

# Colors
color0='#030C1C'
color1='#263C87'
color2='#2F4598'
color3='#454AC6'
color4='#595AEE'
color5='#664FFB'
color6='#5D90FD'
color7='#1f74e5'
color8='#7b90ac'
color9='#263C87'
color10='#2F4598'
color11='#454AC6'
color12='#595AEE'
color13='#664FFB'
color14='#5D90FD'
color15='#1f74e5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
